#!/usr/bin/env python3
"""Generate 00000_safe_full_schema.sql from numbered migrations (idempotent transforms)."""
from __future__ import annotations

import re
from pathlib import Path

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "migrations"
OUT = MIGRATIONS_DIR / "00000_safe_full_schema.sql"

SKIP_FILES = {"00000_safe_full_schema.sql"}


def wrap_enum_types(sql: str) -> str:
    """Wrap CREATE TYPE ... AS ENUM (...) ; in DO blocks."""
    pattern = re.compile(
        r"CREATE TYPE\s+(\w+)\s+AS\s+ENUM\s*\([^;]+\);",
        re.IGNORECASE | re.DOTALL,
    )

    def repl(m: re.Match) -> str:
        stmt = m.group(0).rstrip().rstrip(";")
        return (
            f"DO $$\nBEGIN\n  {stmt};\nEXCEPTION\n  WHEN duplicate_object THEN NULL;\nEND $$;"
        )

    return pattern.sub(repl, sql)


def add_if_not_exists_tables(sql: str) -> str:
    return re.sub(
        r"CREATE TABLE\s+(?!IF\s+NOT\s+EXISTS)",
        "CREATE TABLE IF NOT EXISTS ",
        sql,
        flags=re.IGNORECASE,
    )


def add_if_not_exists_index(sql: str) -> str:
    sql = re.sub(
        r"CREATE UNIQUE INDEX\s+(?!IF\s+NOT\s+EXISTS)",
        "CREATE UNIQUE INDEX IF NOT EXISTS ",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"CREATE INDEX\s+(?!IF\s+NOT\s+EXISTS)",
        "CREATE INDEX IF NOT EXISTS ",
        sql,
        flags=re.IGNORECASE,
    )
    return sql


def prepend_drop_policy(sql: str) -> str:
    """
    Before every CREATE POLICY "name" ON table ... insert DROP POLICY IF EXISTS.
    Uses a regex on the policy header line only (avoids swallowing CREATE TABLE / $$ bodies).
    """

    def repl(m: re.Match) -> str:
        name, table = m.group(1), m.group(2)
        return f'DROP POLICY IF EXISTS "{name}" ON {table};\n{m.group(0)}'

    return re.sub(
        r'CREATE\s+POLICY\s+"([^"]+)"\s+ON\s+([a-zA-Z0-9_.]+)\s',
        repl,
        sql,
        flags=re.IGNORECASE | re.MULTILINE,
    )


def fix_push_tokens_migration_block(sql: str) -> str:
    """Make 00028 push_tokens dedupe + unique constraint safe to re-run."""
    old = """-- Replace (user_id, token) unique with (user_id, platform) for token refresh upserts.
ALTER TABLE push_tokens DROP CONSTRAINT IF EXISTS push_tokens_user_id_token_key;

-- Keep the newest row per (user_id, platform) before adding the new unique constraint.
DELETE FROM push_tokens
WHERE ctid NOT IN (
  SELECT DISTINCT ON (user_id, platform) ctid
  FROM push_tokens
  ORDER BY user_id, platform, created_at DESC NULLS LAST, id DESC
);

ALTER TABLE push_tokens
  ADD CONSTRAINT push_tokens_user_id_platform_key UNIQUE (user_id, platform);"""
    new = """-- Replace (user_id, token) unique with (user_id, platform) for token refresh upserts.
ALTER TABLE push_tokens DROP CONSTRAINT IF EXISTS push_tokens_user_id_token_key;

-- Dedupe only before first add of (user_id, platform) unique (safe on re-run).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON t.relnamespace = n.oid
    WHERE n.nspname = 'public' AND t.relname = 'push_tokens'
      AND c.conname = 'push_tokens_user_id_platform_key'
  ) THEN
    DELETE FROM public.push_tokens
    WHERE ctid NOT IN (
      SELECT DISTINCT ON (user_id, platform) ctid
      FROM public.push_tokens
      ORDER BY user_id, platform, created_at DESC NULLS LAST, id DESC
    );
  END IF;
END $$;

DO $$
BEGIN
  ALTER TABLE public.push_tokens
    ADD CONSTRAINT push_tokens_user_id_platform_key UNIQUE (user_id, platform);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;"""
    if old not in sql:
        return sql
    return sql.replace(old, new, 1)


def ensure_drop_trigger_before_create(sql: str) -> str:
    """Before CREATE TRIGGER name ON table, add DROP TRIGGER IF EXISTS name ON table;"""
    pattern = re.compile(
        r"CREATE\s+TRIGGER\s+(\w+)\s+[^;]+ON\s+([a-zA-Z0-9_.]+)\s+",
        re.IGNORECASE | re.DOTALL,
    )

    def repl(m: re.Match) -> str:
        tname, tbl = m.group(1), m.group(2)
        return f"DROP TRIGGER IF EXISTS {tname} ON {tbl};\n{m.group(0)}"

    return pattern.sub(repl, sql)


def main() -> None:
    files = sorted(
        p
        for p in MIGRATIONS_DIR.glob("*.sql")
        if p.name not in SKIP_FILES and p.name != OUT.name
    )
    parts: list[str] = [
        "-- =============================================================================\n",
        "-- Miami Science Tracker — SAFE FULL SCHEMA (idempotent)\n",
        "-- =============================================================================\n",
        "-- Generated by supabase/scripts/generate_safe_full_schema.py — do not edit by hand.\n",
        "-- Run in Supabase SQL Editor on a DB that may already have partial schema.\n",
        "-- Uses: CREATE IF NOT EXISTS, DROP POLICY IF EXISTS, DO $$ duplicate_object, etc.\n",
        "-- After this succeeds, you can retire conflicting 00001–00032 migrations on new envs\n",
        "-- or keep them skipped; avoid re-applying old migrations that lack IF NOT EXISTS.\n",
        "-- =============================================================================\n\n",
    ]
    for path in files:
        parts.append(f"\n-- >>> FROM {path.name} <<<\n\n")
        raw = path.read_text()
        parts.append(raw)
        parts.append("\n")

    body = "".join(parts)
    body = wrap_enum_types(body)
    body = add_if_not_exists_tables(body)
    body = add_if_not_exists_index(body)
    body = prepend_drop_policy(body)
    body = ensure_drop_trigger_before_create(body)
    body = fix_push_tokens_migration_block(body)

    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT} ({len(body)} bytes, {len(body.splitlines())} lines)")


if __name__ == "__main__":
    main()
