-- =============================================================================
-- Miami Science Tracker — SAFE FULL SCHEMA (idempotent)
-- =============================================================================
-- Generated by supabase/scripts/generate_safe_full_schema.py — do not edit by hand.
-- Run in Supabase SQL Editor on a DB that may already have partial schema.
-- Uses: CREATE IF NOT EXISTS, DROP POLICY IF EXISTS, DO $$ duplicate_object, etc.
-- After this succeeds, you can retire conflicting 00001–00032 migrations on new envs
-- or keep them skipped; avoid re-applying old migrations that lack IF NOT EXISTS.
-- =============================================================================


-- >>> FROM 00001_initial_schema.sql <<<

-- Miami Science Tracker — Initial schema
-- Run this in Supabase SQL editor or via supabase db push

-- Enable UUID extension if not already
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Custom role type
DO $$
BEGIN
  CREATE TYPE app_role AS ENUM ('customer', 'affiliate', 'admin');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- User roles (one row per user, one role)
CREATE TABLE IF NOT EXISTS user_roles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL DEFAULT 'customer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- Workouts
CREATE TABLE IF NOT EXISTS workouts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  started_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Workout entries (exercises within a workout)
CREATE TABLE IF NOT EXISTS workout_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workout_id UUID NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
  exercise_name TEXT NOT NULL,
  sets INT,
  reps INT,
  weight DECIMAL(10,2),
  notes TEXT
);

-- Body metrics
CREATE TABLE IF NOT EXISTS body_metrics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recorded_at TIMESTAMPTZ NOT NULL,
  weight_kg DECIMAL(6,2),
  measurements JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Protocols (user-defined routines)
CREATE TABLE IF NOT EXISTS protocols (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Protocol adherence logs
DO $$
BEGIN
  CREATE TYPE adherence_type AS ENUM ('completed', 'partial', 'skipped');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
CREATE TABLE IF NOT EXISTS protocol_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  protocol_id UUID NOT NULL REFERENCES protocols(id) ON DELETE CASCADE,
  logged_at DATE NOT NULL,
  adherence adherence_type NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Products (reference for shop links)
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  image_url TEXT,
  shop_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Product links (shop/reorder URLs)
CREATE TABLE IF NOT EXISTS product_links (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  url TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
);

-- Supplies (user supply tracker)
CREATE TABLE IF NOT EXISTS supplies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  current_count INT NOT NULL DEFAULT 0,
  threshold_alert INT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Orders (synced from ecommerce later)
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  external_id TEXT,
  status TEXT NOT NULL,
  total_cents INT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Shipments
CREATE TABLE IF NOT EXISTS shipments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  carrier TEXT,
  tracking_number TEXT,
  status TEXT NOT NULL,
  estimated_delivery DATE,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reward points ledger
CREATE TABLE IF NOT EXISTS reward_points_ledger (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount_delta INT NOT NULL,
  reason TEXT NOT NULL,
  reference_type TEXT,
  reference_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Affiliate profiles
DO $$
BEGIN
  CREATE TYPE affiliate_status AS ENUM ('active', 'paused', 'suspended');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
CREATE TABLE IF NOT EXISTS affiliate_profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  referral_code TEXT NOT NULL UNIQUE,
  coupon_code TEXT,
  status affiliate_status NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- Affiliate stats cache (for dashboard; sync from SliceWP later)
CREATE TABLE IF NOT EXISTS affiliate_stats_cache (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period TEXT NOT NULL,
  clicks INT NOT NULL DEFAULT 0,
  conversions INT NOT NULL DEFAULT 0,
  commission_cents INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, period)
);

-- Chat rooms
CREATE TABLE IF NOT EXISTS chat_rooms (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_affiliate_only BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Chat room members
CREATE TABLE IF NOT EXISTS chat_room_members (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(room_id, user_id)
);

-- Chat messages
CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  edited_at TIMESTAMPTZ
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Moderation reports
CREATE TABLE IF NOT EXISTS moderation_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  reporter_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  message_id UUID NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_workouts_user_id ON workouts(user_id);
CREATE INDEX IF NOT EXISTS idx_workout_entries_workout_id ON workout_entries(workout_id);
CREATE INDEX IF NOT EXISTS idx_body_metrics_user_id ON body_metrics(user_id);
CREATE INDEX IF NOT EXISTS idx_protocols_user_id ON protocols(user_id);
CREATE INDEX IF NOT EXISTS idx_protocol_logs_protocol_id ON protocol_logs(protocol_id);
CREATE INDEX IF NOT EXISTS idx_supplies_user_id ON supplies(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_shipments_order_id ON shipments(order_id);
CREATE INDEX IF NOT EXISTS idx_reward_points_ledger_user_id ON reward_points_ledger(user_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_profiles_user_id ON affiliate_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_stats_cache_user_id ON affiliate_stats_cache(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_room_id ON chat_messages(room_id);
CREATE INDEX IF NOT EXISTS idx_chat_room_members_room_id ON chat_room_members(room_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_moderation_reports_message_id ON moderation_reports(message_id);

-- RLS: enable on all tables (policies to be added per-table)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE body_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE protocol_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplies ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE reward_points_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_stats_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_room_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE moderation_reports ENABLE ROW LEVEL SECURITY;

-- Basic RLS policies (user sees own data; admin policies can be added via service role or custom claims)
DROP POLICY IF EXISTS "Users can read own profile" ON profiles;
CREATE POLICY "Users can read own profile" ON profiles FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can read own role" ON user_roles;
CREATE POLICY "Users can read own role" ON user_roles FOR SELECT USING (auth.uid() = user_id);
-- Insert/update user_roles restricted to service role or admin (add later)

DROP POLICY IF EXISTS "Users can CRUD own workouts" ON workouts;
CREATE POLICY "Users can CRUD own workouts" ON workouts FOR ALL USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can CRUD workout_entries for own workouts" ON workout_entries;
CREATE POLICY "Users can CRUD workout_entries for own workouts" ON workout_entries FOR ALL
  USING (EXISTS (SELECT 1 FROM workouts w WHERE w.id = workout_entries.workout_id AND w.user_id = auth.uid()));
DROP POLICY IF EXISTS "Users can CRUD own body_metrics" ON body_metrics;
CREATE POLICY "Users can CRUD own body_metrics" ON body_metrics FOR ALL USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can CRUD own protocols" ON protocols;
CREATE POLICY "Users can CRUD own protocols" ON protocols FOR ALL USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can CRUD protocol_logs for own protocols" ON protocol_logs;
CREATE POLICY "Users can CRUD protocol_logs for own protocols" ON protocol_logs FOR ALL
  USING (EXISTS (SELECT 1 FROM protocols p WHERE p.id = protocol_logs.protocol_id AND p.user_id = auth.uid()));

DROP POLICY IF EXISTS "Products are readable by all authenticated" ON products;
CREATE POLICY "Products are readable by all authenticated" ON products FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Product links are readable by all authenticated" ON product_links;
CREATE POLICY "Product links are readable by all authenticated" ON product_links FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Users can CRUD own supplies" ON supplies;
CREATE POLICY "Users can CRUD own supplies" ON supplies FOR ALL USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can read own orders" ON orders;
CREATE POLICY "Users can read own orders" ON orders FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can read shipments for own orders" ON shipments;
CREATE POLICY "Users can read shipments for own orders" ON shipments FOR SELECT
  USING (EXISTS (SELECT 1 FROM orders o WHERE o.id = shipments.order_id AND o.user_id = auth.uid()));
DROP POLICY IF EXISTS "Users can read own reward_points_ledger" ON reward_points_ledger;
CREATE POLICY "Users can read own reward_points_ledger" ON reward_points_ledger FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can read own affiliate_profile" ON affiliate_profiles;
CREATE POLICY "Users can read own affiliate_profile" ON affiliate_profiles FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can read own affiliate_stats_cache" ON affiliate_stats_cache;
CREATE POLICY "Users can read own affiliate_stats_cache" ON affiliate_stats_cache FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Chat rooms readable by authenticated" ON chat_rooms;
CREATE POLICY "Chat rooms readable by authenticated" ON chat_rooms FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Chat room members can read own memberships" ON chat_room_members;
CREATE POLICY "Chat room members can read own memberships" ON chat_room_members FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Chat messages readable by room members" ON chat_messages;
CREATE POLICY "Chat messages readable by room members" ON chat_messages FOR SELECT
  USING (EXISTS (SELECT 1 FROM chat_room_members crm WHERE crm.room_id = chat_messages.room_id AND crm.user_id = auth.uid()));
DROP POLICY IF EXISTS "Chat messages insert by room members" ON chat_messages;
CREATE POLICY "Chat messages insert by room members" ON chat_messages FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM chat_room_members crm WHERE crm.room_id = chat_messages.room_id AND crm.user_id = auth.uid()));

DROP POLICY IF EXISTS "Users can read own notifications" ON notifications;
CREATE POLICY "Users can read own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own notifications (read_at)" ON notifications;
CREATE POLICY "Users can update own notifications (read_at)" ON notifications FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create moderation_reports" ON moderation_reports;
CREATE POLICY "Users can create moderation_reports" ON moderation_reports FOR INSERT WITH CHECK (auth.uid() = reporter_id);
DROP POLICY IF EXISTS "Users can read own reports" ON moderation_reports;
CREATE POLICY "Users can read own reports" ON moderation_reports FOR SELECT USING (auth.uid() = reporter_id);

-- Trigger: create profile and assign default role on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id) VALUES (NEW.id);
  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'customer');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- >>> FROM 00002_phase4_profile_workouts_supplies.sql <<<

-- Phase 4: Profile onboarding, workout tracker, supply tracker fields
-- Run after 00001_initial_schema.sql

-- Profiles: onboarding fields
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS fitness_goal TEXT,
  ADD COLUMN IF NOT EXISTS preferred_units TEXT DEFAULT 'metric',
  ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'America/New_York';

-- Workouts: type, duration, optional bodyweight and scores
ALTER TABLE workouts
  ADD COLUMN IF NOT EXISTS workout_type TEXT,
  ADD COLUMN IF NOT EXISTS duration_minutes INT,
  ADD COLUMN IF NOT EXISTS bodyweight_kg DECIMAL(6,2),
  ADD COLUMN IF NOT EXISTS energy_score INT,
  ADD COLUMN IF NOT EXISTS recovery_score INT;

-- Supplies: notes, daily use for days-left estimate, starting quantity
ALTER TABLE supplies
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS daily_use_estimate DECIMAL(6,2),
  ADD COLUMN IF NOT EXISTS starting_quantity INT;


-- >>> FROM 00003_phase5_orders_shipments_rewards.sql <<<

-- Phase 5: Orders, shipments, rewards display fields
-- Run after 00002

-- Orders: display and reorder support
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS order_number TEXT,
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS item_count INT,
  ADD COLUMN IF NOT EXISTS shop_url TEXT;

-- Shipments: explicit shipped date
ALTER TABLE shipments
  ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ;

-- Reward ledger: optional display description
ALTER TABLE reward_points_ledger
  ADD COLUMN IF NOT EXISTS description TEXT;


-- >>> FROM 00004_phase6_affiliate_community_moderation.sql <<<

-- Phase 6: Affiliate display, community rooms, moderation
-- Run after 00003

-- Affiliate profiles: optional display fields
ALTER TABLE affiliate_profiles
  ADD COLUMN IF NOT EXISTS referral_link TEXT,
  ADD COLUMN IF NOT EXISTS payout_status TEXT DEFAULT 'pending';

-- Moderation reports: admin review tracking
ALTER TABLE moderation_reports
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

-- RLS: admin can read and update all moderation_reports
CREATE OR REPLACE FUNCTION public.has_role_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

DROP POLICY IF EXISTS "Admin can read all moderation_reports" ON moderation_reports;
DROP POLICY IF EXISTS "Admin can read all moderation_reports" ON moderation_reports;
CREATE POLICY "Admin can read all moderation_reports" ON moderation_reports
  FOR SELECT USING (public.has_role_admin());

DROP POLICY IF EXISTS "Admin can update moderation_reports" ON moderation_reports;
DROP POLICY IF EXISTS "Admin can update moderation_reports" ON moderation_reports;
CREATE POLICY "Admin can update moderation_reports" ON moderation_reports
  FOR UPDATE USING (public.has_role_admin());

-- RLS: authenticated users can join any chat room (insert own membership)
DROP POLICY IF EXISTS "Users can join chat rooms" ON chat_room_members;
DROP POLICY IF EXISTS "Users can join chat rooms" ON chat_room_members;
CREATE POLICY "Users can join chat rooms" ON chat_room_members
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Seed default chat rooms if not present
INSERT INTO chat_rooms (slug, name, is_affiliate_only)
VALUES
  ('community', 'Community', false),
  ('affiliates', 'Affiliates', true)
ON CONFLICT (slug) DO NOTHING;


-- >>> FROM 00005_phase7_referred_orders_moderation_room.sql <<<

-- Phase 7: Referred orders, moderation context
-- Run after 00004

-- Orders: track which affiliate referred (for referred-orders list)
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS referred_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_orders_referred_by ON orders(referred_by_user_id);

-- Moderation: room context for "view in context" link
ALTER TABLE moderation_reports
  ADD COLUMN IF NOT EXISTS room_id UUID REFERENCES chat_rooms(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_moderation_reports_room_id ON moderation_reports(room_id);

-- RLS: admin can read all profiles (for affiliate list display names)
DROP POLICY IF EXISTS "Admin can read all profiles" ON profiles;
CREATE POLICY "Admin can read all profiles" ON profiles
  FOR SELECT USING (public.has_role_admin());

-- RLS: admin can manage affiliate_profiles (any user)
DROP POLICY IF EXISTS "Admin can read all affiliate_profiles" ON affiliate_profiles;
CREATE POLICY "Admin can read all affiliate_profiles" ON affiliate_profiles
  FOR SELECT USING (public.has_role_admin());
DROP POLICY IF EXISTS "Admin can insert affiliate_profiles" ON affiliate_profiles;
CREATE POLICY "Admin can insert affiliate_profiles" ON affiliate_profiles
  FOR INSERT WITH CHECK (public.has_role_admin());
DROP POLICY IF EXISTS "Admin can update affiliate_profiles" ON affiliate_profiles;
CREATE POLICY "Admin can update affiliate_profiles" ON affiliate_profiles
  FOR UPDATE USING (public.has_role_admin());

-- RLS: admin can update user_roles (e.g. set affiliate)
DROP POLICY IF EXISTS "Admin can update user_roles" ON user_roles;
CREATE POLICY "Admin can update user_roles" ON user_roles
  FOR UPDATE USING (public.has_role_admin());


-- >>> FROM 00006_phase8_orders_user_id_nullable.sql <<<

-- Phase 8B: Store webhook ingestion — allow orders without a linked user until mapping exists
-- Run after 00005

-- Orders: user_id may be null when order is synced from store before customer/tracker mapping
ALTER TABLE orders
  ALTER COLUMN user_id DROP NOT NULL;

-- RLS unchanged: "Users can read own orders" (auth.uid() = user_id) — unlinked orders (user_id IS NULL) are not visible to any user until linked.


-- >>> FROM 00007_phase8c_shipments_external_id.sql <<<

-- Phase 8C: Shipment webhook ingestion — stable id for upsert
-- Run after 00006

ALTER TABLE shipments
  ADD COLUMN IF NOT EXISTS external_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_shipments_external_id ON shipments(external_id) WHERE external_id IS NOT NULL;


-- >>> FROM 00008_habits_refill_check_ins_announcements.sql <<<

-- Phase: Habits & Refill — check-ins and announcements
-- Run after 00007

-- Daily check-ins: one row per user per calendar day
CREATE TABLE IF NOT EXISTS check_ins (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  check_in_date DATE NOT NULL,
  routine_done BOOLEAN NOT NULL DEFAULT false,
  worked_out BOOLEAN NOT NULL DEFAULT false,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, check_in_date)
);

CREATE INDEX IF NOT EXISTS idx_check_ins_user_date ON check_ins(user_id, check_in_date DESC);

ALTER TABLE check_ins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own check_ins" ON check_ins;
CREATE POLICY "Users can read own check_ins" ON check_ins FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own check_ins" ON check_ins;
CREATE POLICY "Users can insert own check_ins" ON check_ins FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own check_ins" ON check_ins;
CREATE POLICY "Users can update own check_ins" ON check_ins FOR UPDATE USING (auth.uid() = user_id);

-- Announcements: admin-managed; customers read only
CREATE TABLE IF NOT EXISTS announcements (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title TEXT NOT NULL,
  body TEXT,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_announcements_published ON announcements(published_at DESC) WHERE published_at IS NOT NULL;

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read published announcements; admins can read all (for future management UI)
DROP POLICY IF EXISTS "Authenticated can read published announcements" ON announcements;
CREATE POLICY "Authenticated can read published announcements" ON announcements FOR SELECT TO authenticated
  USING (published_at IS NOT NULL AND published_at <= now());
DROP POLICY IF EXISTS "Admins can read all announcements" ON announcements;
CREATE POLICY "Admins can read all announcements" ON announcements FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin'));

-- Admins can manage announcements (via role check)
DROP POLICY IF EXISTS "Admins can insert announcements" ON announcements;
CREATE POLICY "Admins can insert announcements" ON announcements FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin'));
DROP POLICY IF EXISTS "Admins can update announcements" ON announcements;
CREATE POLICY "Admins can update announcements" ON announcements FOR UPDATE
  USING (EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin'));
DROP POLICY IF EXISTS "Admins can delete announcements" ON announcements;
CREATE POLICY "Admins can delete announcements" ON announcements FOR DELETE
  USING (EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin'));


-- >>> FROM 00009_rewards_redemption_insert.sql <<<

-- Allow users to insert their own reward_points_ledger rows (for redemption).
-- Run after 00008

DROP POLICY IF EXISTS "Users can insert own reward_points_ledger" ON reward_points_ledger;
CREATE POLICY "Users can insert own reward_points_ledger" ON reward_points_ledger
  FOR INSERT WITH CHECK (auth.uid() = user_id);


-- >>> FROM 00010_products_favorites.sql <<<

-- Products: optional description, price, category for catalog
-- User favorites: user_id + product_id
-- Run after 00009

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS price_cents INT,
  ADD COLUMN IF NOT EXISTS category TEXT;

CREATE TABLE IF NOT EXISTS user_favorites (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_user_favorites_user_id ON user_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_product_id ON user_favorites(product_id);

ALTER TABLE user_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own user_favorites" ON user_favorites;
CREATE POLICY "Users can read own user_favorites" ON user_favorites
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own user_favorites" ON user_favorites;
CREATE POLICY "Users can insert own user_favorites" ON user_favorites
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own user_favorites" ON user_favorites;
CREATE POLICY "Users can delete own user_favorites" ON user_favorites
  FOR DELETE USING (auth.uid() = user_id);


-- >>> FROM 00011_shipment_inventory_updated.sql <<<

-- Shipment-to-inventory: track when user has added delivered shipment to their stack
-- Run after 00010

ALTER TABLE shipments
  ADD COLUMN IF NOT EXISTS inventory_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS inventory_updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

-- Allow users to update shipments for their own orders (e.g. set inventory_updated_at)
DROP POLICY IF EXISTS "Users can update shipments for own orders" ON shipments;
CREATE POLICY "Users can update shipments for own orders" ON shipments
  FOR UPDATE
  USING (EXISTS (SELECT 1 FROM orders o WHERE o.id = shipments.order_id AND o.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM orders o WHERE o.id = shipments.order_id AND o.user_id = auth.uid()));


-- >>> FROM 00012_customer_mappings_woo_backfill.sql <<<

-- Customer mapping: link app users to WooCommerce customers for order attribution and backfill.
-- Optional orders columns for audit/matching (customer_email, woo_customer_id).
-- Run after 00011.

CREATE TABLE IF NOT EXISTS customer_mappings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  woo_customer_id BIGINT NOT NULL,
  customer_email TEXT NOT NULL,
  match_source TEXT NOT NULL CHECK (match_source IN ('email', 'manual', 'woo_customer_id', 'imported')),
  matched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id),
  UNIQUE(woo_customer_id)
);

CREATE INDEX IF NOT EXISTS idx_customer_mappings_user_id ON customer_mappings(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_mappings_woo_customer_id ON customer_mappings(woo_customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_mappings_customer_email ON customer_mappings(LOWER(TRIM(customer_email)));

ALTER TABLE customer_mappings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own customer_mapping" ON customer_mappings;
CREATE POLICY "Users can read own customer_mapping" ON customer_mappings
  FOR SELECT USING (auth.uid() = user_id);

-- Insert/update/delete only via service role (no policy = only service role can write).

-- Optional: store customer email and WooCommerce customer id on order for audit and matching.
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS customer_email TEXT,
  ADD COLUMN IF NOT EXISTS woo_customer_id BIGINT;


-- >>> FROM 00013_notification_preferences_push_tokens.sql <<<

-- Notification preferences and push token placeholder.
-- Run after 00012.

-- Notification preferences: one row per user; defaults apply when missing.
CREATE TABLE IF NOT EXISTS notification_preferences (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reorder_reminders BOOLEAN NOT NULL DEFAULT true,
  comeback_reminders BOOLEAN NOT NULL DEFAULT true,
  weekly_recap BOOLEAN NOT NULL DEFAULT true,
  announcements BOOLEAN NOT NULL DEFAULT true,
  email_enabled BOOLEAN NOT NULL DEFAULT true,
  push_enabled BOOLEAN NOT NULL DEFAULT false,
  email_unsubscribe_token TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

CREATE INDEX IF NOT EXISTS idx_notification_preferences_user_id ON notification_preferences(user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_preferences_email_unsubscribe_token
  ON notification_preferences(email_unsubscribe_token)
  WHERE email_unsubscribe_token IS NOT NULL;

ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own notification_preferences" ON notification_preferences;
CREATE POLICY "Users can read own notification_preferences" ON notification_preferences
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own notification_preferences" ON notification_preferences;
CREATE POLICY "Users can insert own notification_preferences" ON notification_preferences
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own notification_preferences" ON notification_preferences;
CREATE POLICY "Users can update own notification_preferences" ON notification_preferences
  FOR UPDATE USING (auth.uid() = user_id);

-- Push tokens: placeholder for future Expo / OneSignal integration.
CREATE TABLE IF NOT EXISTS push_tokens (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, token)
);

CREATE INDEX IF NOT EXISTS idx_push_tokens_user_id ON push_tokens(user_id);

ALTER TABLE push_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own push_tokens" ON push_tokens;
CREATE POLICY "Users can read own push_tokens" ON push_tokens FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own push_tokens" ON push_tokens;
CREATE POLICY "Users can insert own push_tokens" ON push_tokens FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own push_tokens" ON push_tokens;
CREATE POLICY "Users can delete own push_tokens" ON push_tokens FOR DELETE USING (auth.uid() = user_id);


-- >>> FROM 00014_notification_log.sql <<<

-- Notification log for auditability and throttling.
-- Run after 00013.

CREATE TABLE IF NOT EXISTS notification_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL,
  channel TEXT NOT NULL,
  status TEXT NOT NULL,
  reason TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notification_log_user_id ON notification_log(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_log_created_at ON notification_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_log_user_type_sent ON notification_log(user_id, notification_type, sent_at DESC) WHERE sent_at IS NOT NULL;

ALTER TABLE notification_log ENABLE ROW LEVEL SECURITY;

-- Only admins can read (for admin log view). Inserts come from service role only (no INSERT policy).
DROP POLICY IF EXISTS "Admins can read notification_log" ON notification_log;
CREATE POLICY "Admins can read notification_log" ON notification_log
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );


-- >>> FROM 00015_products_external_id.sql <<<

-- Products: external_id for WooCommerce (and other store) sync idempotency.
-- Run after 00014.

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS external_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_external_id ON products(external_id) WHERE external_id IS NOT NULL;


-- >>> FROM 00016_integration_sync_log.sql <<<

-- Integration sync log for diagnostics (last run summary only; no secrets).
-- Run after 00015.

CREATE TABLE IF NOT EXISTS integration_sync_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  integration TEXT NOT NULL,
  last_run_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  summary JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_integration_sync_log_integration ON integration_sync_log(integration);
CREATE INDEX IF NOT EXISTS idx_integration_sync_log_last_run_at ON integration_sync_log(last_run_at DESC);

ALTER TABLE integration_sync_log ENABLE ROW LEVEL SECURITY;

-- Admins can read for diagnostics. Writes use service role (bypasses RLS).
DROP POLICY IF EXISTS "Admins can read integration_sync_log" ON integration_sync_log;
CREATE POLICY "Admins can read integration_sync_log" ON integration_sync_log
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );


-- >>> FROM 00017_carts.sql <<<

-- Cart and cart_items for in-app ordering prep. One cart per user; items reference products.
-- Run after 00016.

CREATE TABLE IF NOT EXISTS carts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cart_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  cart_id UUID NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(cart_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_carts_user_id ON carts(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON cart_items(cart_id);

ALTER TABLE carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own cart" ON carts;
CREATE POLICY "Users can read own cart" ON carts FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own cart" ON carts;
CREATE POLICY "Users can insert own cart" ON carts FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own cart" ON carts;
CREATE POLICY "Users can update own cart" ON carts FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can read own cart_items" ON cart_items;
CREATE POLICY "Users can read own cart_items" ON cart_items FOR SELECT
  USING (EXISTS (SELECT 1 FROM carts c WHERE c.id = cart_items.cart_id AND c.user_id = auth.uid()));
DROP POLICY IF EXISTS "Users can insert own cart_items" ON cart_items;
CREATE POLICY "Users can insert own cart_items" ON cart_items FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM carts c WHERE c.id = cart_items.cart_id AND c.user_id = auth.uid()));
DROP POLICY IF EXISTS "Users can update own cart_items" ON cart_items;
CREATE POLICY "Users can update own cart_items" ON cart_items FOR UPDATE
  USING (EXISTS (SELECT 1 FROM carts c WHERE c.id = cart_items.cart_id AND c.user_id = auth.uid()));
DROP POLICY IF EXISTS "Users can delete own cart_items" ON cart_items;
CREATE POLICY "Users can delete own cart_items" ON cart_items FOR DELETE
  USING (EXISTS (SELECT 1 FROM carts c WHERE c.id = cart_items.cart_id AND c.user_id = auth.uid()));


-- >>> FROM 00018_redeem_reward_points_rpc.sql <<<

-- Atomic reward redemption: balance check + insert in one transaction with row lock.
-- Prevents double-spend when two concurrent requests try to redeem.
-- Run after 00017.

CREATE OR REPLACE FUNCTION redeem_reward_points(
  p_user_id uuid,
  p_option_id text,
  p_points integer,
  p_reason text,
  p_description text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, auth
AS $$
DECLARE
  current_balance integer;
BEGIN
  IF auth.uid() IS DISTINCT FROM p_user_id THEN
    RAISE EXCEPTION 'Unauthorized: can only redeem for yourself';
  END IF;

  -- Lock user's ledger rows so concurrent redemptions are serialized.
  SELECT COALESCE(SUM(amount_delta), 0) INTO current_balance
  FROM reward_points_ledger
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF current_balance < p_points THEN
    RAISE EXCEPTION 'Not enough points. You have % pts; this option requires % pts.', current_balance, p_points;
  END IF;

  INSERT INTO reward_points_ledger (user_id, amount_delta, reason, description, reference_type, reference_id)
  VALUES (p_user_id, -p_points, p_reason, p_description, 'redemption', p_option_id);
END;
$$;

COMMENT ON FUNCTION redeem_reward_points(uuid, text, integer, text, text) IS
  'Atomic redemption: checks balance under row lock and inserts negative ledger entry. Prevents double-spend.';

GRANT EXECUTE ON FUNCTION redeem_reward_points(uuid, text, integer, text, text) TO authenticated;


-- >>> FROM 00019_exercises.sql <<<

-- Exercise library: optional images, category, description. Used for visual cards and detail.
-- workout_entries.exercise_name stays the source of truth; exercises table enriches display.
-- Run after 00018.

CREATE TABLE IF NOT EXISTS exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  image_url text,
  category text,
  muscle_group text,
  description text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_exercises_slug ON exercises (slug);
CREATE INDEX IF NOT EXISTS idx_exercises_name ON exercises (name);

COMMENT ON TABLE exercises IS 'Exercise library for display (images, category). workout_entries reference by name.';

-- RLS: anyone can read; only service role or admin can write (future).
ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Exercises are readable by everyone" ON exercises;
CREATE POLICY "Exercises are readable by everyone"
  ON exercises FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Exercises are readable by anon for public catalog" ON exercises;
CREATE POLICY "Exercises are readable by anon for public catalog"
  ON exercises FOR SELECT
  TO anon
  USING (true);


-- >>> FROM 00020_seed_exercises.sql <<<

-- Curated exercise library seed. Safe to re-run: existing rows kept by unique name/slug.
-- Categories: Strength, Cardio, Mobility. Muscle groups: Chest, Back, Legs, Shoulders, Arms, Core.

INSERT INTO exercises (name, slug, category, muscle_group, description) VALUES
  ('Bench Press', 'bench-press', 'Strength', 'Chest', 'Lie on bench, lower bar to chest, press up.'),
  ('Incline Bench Press', 'incline-bench-press', 'Strength', 'Chest', NULL),
  ('Push-Up', 'push-up', 'Strength', 'Chest', NULL),
  ('Cable Fly', 'cable-fly', 'Strength', 'Chest', NULL),
  ('Barbell Row', 'barbell-row', 'Strength', 'Back', 'Hinge at hips, pull bar to lower chest.'),
  ('Pull-Up', 'pull-up', 'Strength', 'Back', NULL),
  ('Lat Pulldown', 'lat-pulldown', 'Strength', 'Back', NULL),
  ('Deadlift', 'deadlift', 'Strength', 'Back', 'Hinge at hips, drive through heels to stand with bar.'),
  ('Romanian Deadlift', 'romanian-deadlift', 'Strength', 'Back', NULL),
  ('Squat', 'squat', 'Strength', 'Legs', 'Squat down with bar on upper back, stand.'),
  ('Leg Press', 'leg-press', 'Strength', 'Legs', NULL),
  ('Lunge', 'lunge', 'Strength', 'Legs', NULL),
  ('Leg Curl', 'leg-curl', 'Strength', 'Legs', NULL),
  ('Calf Raise', 'calf-raise', 'Strength', 'Legs', NULL),
  ('Overhead Press', 'overhead-press', 'Strength', 'Shoulders', 'Press bar or dumbbells overhead.'),
  ('Lateral Raise', 'lateral-raise', 'Strength', 'Shoulders', NULL),
  ('Front Raise', 'front-raise', 'Strength', 'Shoulders', NULL),
  ('Face Pull', 'face-pull', 'Strength', 'Shoulders', NULL),
  ('Barbell Curl', 'barbell-curl', 'Strength', 'Arms', NULL),
  ('Hammer Curl', 'hammer-curl', 'Strength', 'Arms', NULL),
  ('Tricep Pushdown', 'tricep-pushdown', 'Strength', 'Arms', NULL),
  ('Skull Crusher', 'skull-crusher', 'Strength', 'Arms', NULL),
  ('Plank', 'plank', 'Strength', 'Core', 'Hold rigid body on forearms and toes.'),
  ('Crunch', 'crunch', 'Strength', 'Core', NULL),
  ('Russian Twist', 'russian-twist', 'Strength', 'Core', NULL),
  ('Hanging Leg Raise', 'hanging-leg-raise', 'Strength', 'Core', NULL),
  ('Running', 'running', 'Cardio', NULL, NULL),
  ('Cycling', 'cycling', 'Cardio', NULL, NULL),
  ('Rowing Machine', 'rowing-machine', 'Cardio', NULL, NULL),
  ('Jump Rope', 'jump-rope', 'Cardio', NULL, NULL),
  ('Hip Mobility', 'hip-mobility', 'Mobility', 'Legs', NULL),
  ('Shoulder Mobility', 'shoulder-mobility', 'Mobility', 'Shoulders', NULL),
  ('Cat Cow', 'cat-cow', 'Mobility', 'Back', NULL)
ON CONFLICT (name) DO NOTHING;


-- >>> FROM 00021_auto_customer_link_support.sql <<<

-- Support automatic WooCommerce customer linking by email.
-- 1. Allow match_source 'auto_email' in customer_mappings.
-- 2. Throttle auto-link attempts per user via profiles.

-- WooCommerce customer_mappings: add auto_email to allowed match_source.
ALTER TABLE customer_mappings
  DROP CONSTRAINT IF EXISTS customer_mappings_match_source_check;

ALTER TABLE customer_mappings
  ADD CONSTRAINT customer_mappings_match_source_check
  CHECK (match_source IN ('email', 'manual', 'woo_customer_id', 'imported', 'auto_email'));

-- Throttle: only attempt auto-link if last attempt was > 24h ago or never.
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS last_customer_auto_link_attempt_at TIMESTAMPTZ;

COMMENT ON COLUMN profiles.last_customer_auto_link_attempt_at IS 'Last time we attempted automatic WooCommerce customer linking for this user; used to throttle API calls.';


-- >>> FROM 00022_exercise_display_order.sql <<<

-- Featured/curated ordering for exercise library. Lower display_order = show first.
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS display_order integer DEFAULT NULL;
COMMENT ON COLUMN exercises.display_order IS 'Lower = show first in library/browse; null = sort by name';


-- >>> FROM 00023_exercise_library_polish.sql <<<

-- Polish seed: descriptions and featured display_order. Safe to re-run (UPDATE only).

-- Short descriptions where missing or minimal
UPDATE exercises SET description = 'Lie on bench, lower bar to chest, press up.' WHERE slug = 'bench-press' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Incline bench, lower to upper chest, press.' WHERE slug = 'incline-bench-press' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hands on floor, lower chest to floor, push up.' WHERE slug = 'push-up' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Cables at chest height, bring handles together in front.' WHERE slug = 'cable-fly' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hinge at hips, pull bar to lower chest.' WHERE slug = 'barbell-row' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hang from bar, pull until chin over bar.' WHERE slug = 'pull-up' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Pull bar to upper chest, control return.' WHERE slug = 'lat-pulldown' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hinge at hips, drive through heels to stand with bar.' WHERE slug = 'deadlift' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Slight knee bend, hinge at hips, lower bar along legs.' WHERE slug = 'romanian-deadlift' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Squat down with bar on upper back, stand.' WHERE slug = 'squat' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Seated, press platform away with feet.' WHERE slug = 'leg-press' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Step forward, lower back knee toward floor, stand.' WHERE slug = 'lunge' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Curl heels toward glutes (machine or lying).' WHERE slug = 'leg-curl' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Rise onto toes, lower with control.' WHERE slug = 'calf-raise' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Press bar or dumbbells overhead to lockout.' WHERE slug = 'overhead-press' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Raise arms to sides to shoulder height.' WHERE slug = 'lateral-raise' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Raise weight in front to shoulder height.' WHERE slug = 'front-raise' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Pull rope to face, squeeze shoulder blades.' WHERE slug = 'face-pull' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Curl bar to shoulders, lower with control.' WHERE slug = 'barbell-curl' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Curl with neutral grip (thumbs up).' WHERE slug = 'hammer-curl' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Push cable or bar down, extend elbows.' WHERE slug = 'tricep-pushdown' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Lower bar to forehead, extend back up.' WHERE slug = 'skull-crusher' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hold rigid body on forearms and toes.' WHERE slug = 'plank' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Curl shoulders toward hips, controlled.' WHERE slug = 'crunch' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Seated, rotate torso side to side with weight.' WHERE slug = 'russian-twist' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hang from bar, raise legs toward bar.' WHERE slug = 'hanging-leg-raise' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Run at steady or interval pace.' WHERE slug = 'running' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Pedal on bike or stationary bike.' WHERE slug = 'cycling' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Pull handle, drive with legs and arms.' WHERE slug = 'rowing-machine' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Jump over rope, land softly.' WHERE slug = 'jump-rope' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Hip circles, leg swings, stretches.' WHERE slug = 'hip-mobility' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Arm circles, band pull-aparts, stretches.' WHERE slug = 'shoulder-mobility' AND (description IS NULL OR description = '');
UPDATE exercises SET description = 'Alternate arch and round spine on hands and knees.' WHERE slug = 'cat-cow' AND (description IS NULL OR description = '');

-- Featured order: show these first on training home and browse (lower = first)
UPDATE exercises SET display_order = 1  WHERE slug = 'bench-press';
UPDATE exercises SET display_order = 2  WHERE slug = 'squat';
UPDATE exercises SET display_order = 3  WHERE slug = 'deadlift';
UPDATE exercises SET display_order = 4  WHERE slug = 'pull-up';
UPDATE exercises SET display_order = 5  WHERE slug = 'overhead-press';
UPDATE exercises SET display_order = 6  WHERE slug = 'barbell-row';
UPDATE exercises SET display_order = 7  WHERE slug = 'plank';
UPDATE exercises SET display_order = 8  WHERE slug = 'lunge';


-- >>> FROM 00024_profiles_exercise_image_variant.sql <<<

-- Per-user preference: men's or women's exercise image set in training UI.
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS exercise_image_variant TEXT DEFAULT 'men'
  CHECK (exercise_image_variant IN ('men', 'women'));
COMMENT ON COLUMN profiles.exercise_image_variant IS 'Which exercise image set to show: men or women. Default men for backward compatibility.';


-- >>> FROM 00025_exercise_display_order_9_12.sql <<<

-- Next 4 featured exercises: display_order 9–12 (after the original 8).
-- Ensures incline-bench-press, push-up, romanian-deadlift, leg-press show next on Training home and Browse.

UPDATE exercises SET display_order = 9  WHERE slug = 'incline-bench-press';
UPDATE exercises SET display_order = 10 WHERE slug = 'push-up';
UPDATE exercises SET display_order = 11 WHERE slug = 'romanian-deadlift';
UPDATE exercises SET display_order = 12 WHERE slug = 'leg-press';


-- >>> FROM 00026_supply_label_strength_profile_height.sql <<<

-- Supply: label strength (vial/bottle label, for tracking only; no dosing logic).
-- Profile: optional height for BMI display only (informational, not used for recommendations).

ALTER TABLE supplies
  ADD COLUMN IF NOT EXISTS label_strength TEXT;

COMMENT ON COLUMN supplies.label_strength IS 'Label strength as on vial/bottle (e.g. 10mg). Tracking only; not used for dosing.';

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS height_cm DECIMAL(5,2);

COMMENT ON COLUMN profiles.height_cm IS 'Optional height in cm for BMI display only. Not used for any recommendation.';


-- >>> FROM 00027_slicewp_affiliate_stats_rls.sql <<<

-- SliceWP: optional link from app affiliate to SliceWP affiliate id (set by admin).
-- Allow affiliates to upsert their own stats cache rows (SliceWP sync from server-side session).

ALTER TABLE affiliate_profiles
  ADD COLUMN IF NOT EXISTS slicewp_affiliate_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_affiliate_profiles_slicewp_affiliate_id
  ON affiliate_profiles (slicewp_affiliate_id)
  WHERE slicewp_affiliate_id IS NOT NULL;

COMMENT ON COLUMN affiliate_profiles.slicewp_affiliate_id IS
  'SliceWP REST API affiliate id (numeric id as string). Admin-set; speeds up API lookup.';

-- Affiliates can insert/update their own cached stats (written during SliceWP sync in-app).
DROP POLICY IF EXISTS "Users can insert own affiliate_stats_cache" ON affiliate_stats_cache;
CREATE POLICY "Users can insert own affiliate_stats_cache"
  ON affiliate_stats_cache
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own affiliate_stats_cache" ON affiliate_stats_cache;
CREATE POLICY "Users can update own affiliate_stats_cache"
  ON affiliate_stats_cache
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- >>> FROM 00028_push_tokens_updated_at_platform_unique.sql <<<

-- push_tokens: updated_at, NOT NULL platform, one row per user per platform (upsert on token refresh).
-- Adds UPDATE policy for client upserts.

ALTER TABLE push_tokens
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

UPDATE push_tokens SET updated_at = created_at WHERE updated_at IS NULL;

UPDATE push_tokens SET platform = COALESCE(NULLIF(trim(platform), ''), 'web') WHERE platform IS NULL OR trim(platform) = '';

ALTER TABLE push_tokens ALTER COLUMN platform SET NOT NULL;
ALTER TABLE push_tokens ALTER COLUMN platform SET DEFAULT 'web';

-- Replace (user_id, token) unique with (user_id, platform) for token refresh upserts.
ALTER TABLE push_tokens DROP CONSTRAINT IF EXISTS push_tokens_user_id_token_key;

-- Dedupe only before first add of (user_id, platform) unique (safe on re-run).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    JOIN pg_namespace n ON t.relnamespace = n.oid
    WHERE n.nspname = 'public' AND t.relname = 'push_tokens'
      AND c.conname = 'push_tokens_user_id_platform_key'
  ) THEN
    DELETE FROM public.push_tokens
    WHERE ctid NOT IN (
      SELECT DISTINCT ON (user_id, platform) ctid
      FROM public.push_tokens
      ORDER BY user_id, platform, created_at DESC NULLS LAST, id DESC
    );
  END IF;
END $$;

DO $$
BEGIN
  ALTER TABLE public.push_tokens
    ADD CONSTRAINT push_tokens_user_id_platform_key UNIQUE (user_id, platform);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DROP POLICY IF EXISTS "Users can update own push_tokens" ON push_tokens;
CREATE POLICY "Users can update own push_tokens" ON push_tokens
  FOR UPDATE USING (auth.uid() = user_id);

COMMENT ON COLUMN push_tokens.updated_at IS 'Last registration or token refresh';


-- >>> FROM 00029_supply_daily_logs.sql <<<

-- Per-supplement daily "taken" checklist (one row per user/supply/calendar day in user's flow).
-- log_date is YYYY-MM-DD in the user's profile timezone, computed in app code.

CREATE TABLE IF NOT EXISTS supply_daily_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  supply_id UUID NOT NULL REFERENCES supplies(id) ON DELETE CASCADE,
  log_date DATE NOT NULL,
  taken BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, supply_id, log_date)
);

CREATE INDEX IF NOT EXISTS idx_supply_daily_logs_user_date ON supply_daily_logs(user_id, log_date DESC);
CREATE INDEX IF NOT EXISTS idx_supply_daily_logs_supply ON supply_daily_logs(supply_id);

ALTER TABLE supply_daily_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own supply_daily_logs" ON supply_daily_logs;
CREATE POLICY "Users read own supply_daily_logs" ON supply_daily_logs
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users insert own supply_daily_logs" ON supply_daily_logs;
CREATE POLICY "Users insert own supply_daily_logs" ON supply_daily_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users update own supply_daily_logs" ON supply_daily_logs;
CREATE POLICY "Users update own supply_daily_logs" ON supply_daily_logs
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users delete own supply_daily_logs" ON supply_daily_logs;
CREATE POLICY "Users delete own supply_daily_logs" ON supply_daily_logs
  FOR DELETE USING (auth.uid() = user_id);


-- >>> FROM 00030_progress_metrics_goals_photos.sql <<<

-- Section 4: body fat on metrics, profile goals, progress photos metadata

ALTER TABLE body_metrics
  ADD COLUMN IF NOT EXISTS body_fat_percent DECIMAL(5,2);

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS goal_weight_kg DECIMAL(6,2),
  ADD COLUMN IF NOT EXISTS goal_body_fat_percent DECIMAL(5,2);

CREATE TABLE IF NOT EXISTS progress_photos (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recorded_at TIMESTAMPTZ NOT NULL,
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_progress_photos_user_recorded
  ON progress_photos(user_id, recorded_at DESC);

ALTER TABLE progress_photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users CRUD own progress_photos" ON progress_photos;
CREATE POLICY "Users CRUD own progress_photos" ON progress_photos
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- >>> FROM 00031_storage_progress_photos.sql <<<

-- Private bucket for progress photos; path layout: {user_id}/{filename}

INSERT INTO storage.buckets (id, name, public)
VALUES ('progress-photos', 'progress-photos', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "progress_photos_select_own" ON storage.objects;
DROP POLICY IF EXISTS "progress_photos_insert_own" ON storage.objects;
DROP POLICY IF EXISTS "progress_photos_update_own" ON storage.objects;
DROP POLICY IF EXISTS "progress_photos_delete_own" ON storage.objects;

DROP POLICY IF EXISTS "progress_photos_select_own" ON storage.objects;
CREATE POLICY "progress_photos_select_own" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'progress-photos'
    AND split_part(name, '/', 1) = auth.uid()::text
  );

DROP POLICY IF EXISTS "progress_photos_insert_own" ON storage.objects;
CREATE POLICY "progress_photos_insert_own" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'progress-photos'
    AND split_part(name, '/', 1) = auth.uid()::text
  );

DROP POLICY IF EXISTS "progress_photos_update_own" ON storage.objects;
CREATE POLICY "progress_photos_update_own" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'progress-photos'
    AND split_part(name, '/', 1) = auth.uid()::text
  );

DROP POLICY IF EXISTS "progress_photos_delete_own" ON storage.objects;
CREATE POLICY "progress_photos_delete_own" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'progress-photos'
    AND split_part(name, '/', 1) = auth.uid()::text
  );


-- >>> FROM 00032_affiliate_group_chat.sql <<<

-- Section 5: Affiliate team chat — pins, admin flag, read receipts, RLS, realtime

ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_admin_message BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_chat_messages_room_pinned ON chat_messages(room_id) WHERE is_pinned = true;

CREATE TABLE IF NOT EXISTS chat_read_receipts (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
  last_read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, room_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_read_receipts_room ON chat_read_receipts(room_id);

ALTER TABLE chat_read_receipts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own chat receipts" ON chat_read_receipts;
CREATE POLICY "Users read own chat receipts" ON chat_read_receipts
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users upsert own chat receipts" ON chat_read_receipts;
CREATE POLICY "Users upsert own chat receipts" ON chat_read_receipts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users update own chat receipts" ON chat_read_receipts;
CREATE POLICY "Users update own chat receipts" ON chat_read_receipts
  FOR UPDATE USING (auth.uid() = user_id);

-- Mark admin-authored rows for UI (team on the left)
CREATE OR REPLACE FUNCTION public.set_chat_message_admin_flag()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM user_roles WHERE user_id = NEW.user_id AND role = 'admin') THEN
    NEW.is_admin_message := true;
  ELSE
    NEW.is_admin_message := false;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_chat_messages_admin_flag ON chat_messages;
DROP TRIGGER IF EXISTS trg_chat_messages_admin_flag ON chat_messages;
CREATE TRIGGER trg_chat_messages_admin_flag
  BEFORE INSERT ON chat_messages
  FOR EACH ROW
  EXECUTE FUNCTION public.set_chat_message_admin_flag();

-- Replace chat_messages policies for affiliate room access without requiring membership
DROP POLICY IF EXISTS "Chat messages readable by room members" ON chat_messages;
DROP POLICY IF EXISTS "Chat messages insert by room members" ON chat_messages;

DROP POLICY IF EXISTS "Chat messages readable by members or affiliate room" ON chat_messages;
CREATE POLICY "Chat messages readable by members or affiliate room"
  ON chat_messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM chat_room_members crm
      WHERE crm.room_id = chat_messages.room_id AND crm.user_id = auth.uid()
    )
    OR (
      EXISTS (
        SELECT 1 FROM chat_rooms r
        WHERE r.id = chat_messages.room_id AND r.slug = 'affiliates'
      )
      AND EXISTS (
        SELECT 1 FROM user_roles ur
        WHERE ur.user_id = auth.uid() AND ur.role IN ('affiliate', 'admin')
      )
    )
  );

DROP POLICY IF EXISTS "Chat messages insert by members or affiliate room" ON chat_messages;
CREATE POLICY "Chat messages insert by members or affiliate room"
  ON chat_messages FOR INSERT
  WITH CHECK (
    auth.uid() = user_id
    AND (
      EXISTS (
        SELECT 1 FROM chat_room_members crm
        WHERE crm.room_id = chat_messages.room_id AND crm.user_id = auth.uid()
      )
      OR (
        EXISTS (
          SELECT 1 FROM chat_rooms r
          WHERE r.id = chat_messages.room_id AND r.slug = 'affiliates'
        )
        AND EXISTS (
          SELECT 1 FROM user_roles ur
          WHERE ur.user_id = auth.uid() AND ur.role IN ('affiliate', 'admin')
        )
      )
    )
  );

-- Admin-only pin toggle for affiliate room (single pinned message)
CREATE OR REPLACE FUNCTION public.pin_affiliate_chat_message(p_message_id uuid, p_pinned boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_room uuid;
  v_slug text;
BEGIN
  IF NOT public.has_role_admin() THEN
    RAISE EXCEPTION 'not allowed';
  END IF;
  SELECT room_id INTO v_room FROM chat_messages WHERE id = p_message_id;
  IF v_room IS NULL THEN
    RAISE EXCEPTION 'not found';
  END IF;
  SELECT slug INTO v_slug FROM chat_rooms WHERE id = v_room;
  IF v_slug IS DISTINCT FROM 'affiliates' THEN
    RAISE EXCEPTION 'invalid room';
  END IF;
  IF COALESCE(p_pinned, false) THEN
    UPDATE chat_messages SET is_pinned = false WHERE room_id = v_room;
  END IF;
  UPDATE chat_messages SET is_pinned = COALESCE(p_pinned, false) WHERE id = p_message_id;
END;
$$;

REVOKE ALL ON FUNCTION public.pin_affiliate_chat_message(uuid, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pin_affiliate_chat_message(uuid, boolean) TO authenticated;

-- Realtime (idempotent)
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Display name for affiliate room
UPDATE chat_rooms SET name = 'Affiliate team chat' WHERE slug = 'affiliates' AND name = 'Affiliates';


-- >>> FROM 00037_onboarding_tutorial_flag.sql <<<

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS onboarding_tutorial_completed BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN profiles.onboarding_tutorial_completed IS
  'When true, the first-time dashboard tutorial has been dismissed; do not show again.';

UPDATE profiles SET onboarding_tutorial_completed = true;


-- >>> FROM 00038_profile_gender.sql <<<

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS gender TEXT;

ALTER TABLE profiles
  DROP CONSTRAINT IF EXISTS profiles_gender_check;

ALTER TABLE profiles
  ADD CONSTRAINT profiles_gender_check
  CHECK (gender IS NULL OR gender IN ('male', 'female', 'prefer_not_to_say'));

COMMENT ON COLUMN profiles.gender IS
  'male | female | prefer_not_to_say — drives body diagram; NULL uses neutral silhouette.';

